// <auto-generated>

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace KitchenEquipmentDemo.Enterprise.Data.Models
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // equipment
    public class Equipment
    {
        public int EquipmentId { get; set; } // equipment_id (Primary key)
        public string SerialNumber { get; set; } // serial_number (length: 100)
        public string Name { get; set; } // name (length: 100)
        public string Description { get; set; } // description (length: 200)
        public string Condition { get; set; } // condition (length: 20)
        public int UserId { get; set; } // user_id
        public int? SiteId { get; set; } // site_id
        public DateTime CreatedAt { get; set; } // created_at
        public int? CreatedBy { get; set; } // created_by
        public DateTime? UpdatedAt { get; set; } // updated_at
        public int? UpdatedBy { get; set; } // updated_by
        public bool IsDeleted { get; set; } // is_deleted
        public byte[] RowVersion { get; set; } // row_version (length: 8)

        // Reverse navigation

        /// <summary>
        /// Child SiteEquipmentHistory where [site_equipment_history].[equipment_id] point to this entity (FK_hist_equipment)
        /// </summary>
        public virtual ICollection<SiteEquipmentHistory> SiteEquipmentHistory { get; set; } // site_equipment_history.FK_hist_equipment

        // Foreign keys

        /// <summary>
        /// Parent Site pointed by [equipment].([SiteId]) (FK_equipment_site)
        /// </summary>
        public virtual Site Site { get; set; } // FK_equipment_site

        /// <summary>
        /// Parent User pointed by [equipment].([UserId]) (FK_equipment_user)
        /// </summary>
        public virtual User User { get; set; } // FK_equipment_user

        public Equipment()
        {
            CreatedAt = DateTime.UtcNow;
            IsDeleted = false;
            SiteEquipmentHistory = new List<SiteEquipmentHistory>();
        }
    }

}
// </auto-generated>
