// <auto-generated>

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace KitchenEquipmentDemo.Enterprise.Data.Models
{
    // site_equipment_history
    public class SiteEquipmentHistory
    {
        public int Id { get; set; } // id (Primary key)
        public int EquipmentId { get; set; } // equipment_id
        public int? SiteId { get; set; } // site_id
        public string Action { get; set; } // action (length: 20)
        public DateTime ActionAt { get; set; } // action_at
        public int? ActionBy { get; set; } // action_by

        // Foreign keys

        /// <summary>
        /// Parent Equipment pointed by [site_equipment_history].([EquipmentId]) (FK_hist_equipment)
        /// </summary>
        public virtual Equipment Equipment { get; set; } // FK_hist_equipment

        /// <summary>
        /// Parent Site pointed by [site_equipment_history].([SiteId]) (FK_hist_site)
        /// </summary>
        public virtual Site Site { get; set; } // FK_hist_site

        public SiteEquipmentHistory()
        {
            ActionAt = DateTime.UtcNow;
        }
    }

}
// </auto-generated>
