// <auto-generated>

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace KitchenEquipmentDemo.Enterprise.Data.Models
{
    // site
    public class Site
    {
        public int SiteId { get; set; } // site_id (Primary key)
        public int? UserId { get; set; } // user_id
        public string Code { get; set; } // code (length: 100)
        public string Name { get; set; } // name (length: 100)
        public string Description { get; set; } // description (length: 200)
        public bool Active { get; set; } // active
        public DateTime CreatedAt { get; set; } // created_at
        public int? CreatedBy { get; set; } // created_by
        public DateTime? UpdatedAt { get; set; } // updated_at
        public int? UpdatedBy { get; set; } // updated_by
        public bool IsDeleted { get; set; } // is_deleted
        public byte[] RowVersion { get; set; } // row_version (length: 8)

        // Reverse navigation

        /// <summary>
        /// Child Equipment where [equipment].[site_id] point to this entity (FK_equipment_site)
        /// </summary>
        public virtual ICollection<Equipment> Equipment { get; set; } // equipment.FK_equipment_site

        /// <summary>
        /// Child SiteEquipmentHistory where [site_equipment_history].[site_id] point to this entity (FK_hist_site)
        /// </summary>
        public virtual ICollection<SiteEquipmentHistory> SiteEquipmentHistory { get; set; } // site_equipment_history.FK_hist_site

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [site].([UserId]) (FK_site_user)
        /// </summary>
        public virtual User User { get; set; } // FK_site_user

        public Site()
        {
            Active = true;
            CreatedAt = DateTime.UtcNow;
            IsDeleted = false;
            Equipment = new List<Equipment>();
            SiteEquipmentHistory = new List<SiteEquipmentHistory>();
        }
    }

}
// </auto-generated>
