// <auto-generated>

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace KitchenEquipmentDemo.Enterprise.Data.Models
{
    // user
    public class User
    {
        public int UserId { get; set; } // user_id (Primary key)
        public string UserType { get; set; } // user_type (length: 20)
        public string FirstName { get; set; } // first_name (length: 100)
        public string LastName { get; set; } // last_name (length: 100)
        public string EmailAddress { get; set; } // email_address (length: 256)
        public string UserName { get; set; } // user_name (length: 100)
        public byte[] PasswordHash { get; set; } // password_hash (length: 64)
        public byte[] PasswordSalt { get; set; } // password_salt (length: 16)
        public string PasswordAlgo { get; set; } // password_algo (length: 50)
        public byte? PasswordVersion { get; set; } // password_version
        public DateTime CreatedAt { get; set; } // created_at
        public int? CreatedBy { get; set; } // created_by
        public DateTime? UpdatedAt { get; set; } // updated_at
        public int? UpdatedBy { get; set; } // updated_by
        public bool IsDeleted { get; set; } // is_deleted
        public byte[] RowVersion { get; set; } // row_version (length: 8)

        // Reverse navigation

        /// <summary>
        /// Child Equipment where [equipment].[user_id] point to this entity (FK_equipment_user)
        /// </summary>
        public virtual ICollection<Equipment> Equipment { get; set; } // equipment.FK_equipment_user

        /// <summary>
        /// Child Site where [site].[user_id] point to this entity (FK_site_user)
        /// </summary>
        public virtual ICollection<Site> Site { get; set; } // site.FK_site_user

        /// <summary>
        /// Child UserRegistrationRequest where [user_registration_request].[requested_manager] point to this entity (FK_urr_requested_manager)
        /// </summary>
        public virtual ICollection<UserRegistrationRequest> UserRegistrationRequest_RequestedManager { get; set; } // user_registration_request.FK_urr_requested_manager

        /// <summary>
        /// Child UserRegistrationRequest where [user_registration_request].[reviewed_by] point to this entity (FK_urr_reviewed_by)
        /// </summary>
        public virtual ICollection<UserRegistrationRequest> UserRegistrationRequest_ReviewedBy { get; set; } // user_registration_request.FK_urr_reviewed_by

        public User()
        {
            CreatedAt = DateTime.UtcNow;
            IsDeleted = false;
            Equipment = new List<Equipment>();
            Site = new List<Site>();
            UserRegistrationRequest_RequestedManager = new List<UserRegistrationRequest>();
            UserRegistrationRequest_ReviewedBy = new List<UserRegistrationRequest>();
        }
    }

}
// </auto-generated>
