// <auto-generated>

using System;
using System.Data.Entity.Infrastructure;

namespace KitchenEquipmentDemo.Enterprise.Data
{
    public class AppDbContextFactory : IDbContextFactory<AppDbContext>
    {
        public AppDbContext Create()
        {
            return new AppDbContext();
        }
    }
}
// </auto-generated>
