// <auto-generated>

using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.Spatial;
using KitchenEquipmentDemo.Enterprise.Data.Models;

namespace KitchenEquipmentDemo.Enterprise.Data.Mappings
{
    // site
    public class SiteConfiguration : EntityTypeConfiguration<Site>
    {
        public SiteConfiguration()
            : this("dbo")
        {
        }

        public SiteConfiguration(string schema)
        {
            ToTable("site", schema);
            HasKey(x => x.SiteId);

            Property(x => x.SiteId).HasColumnName(@"site_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"user_id").HasColumnType("int").IsOptional();
            Property(x => x.Code).HasColumnName(@"code").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Name).HasColumnName(@"name").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Description).HasColumnName(@"description").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.Active).HasColumnName(@"active").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType("datetime2").IsRequired();
            Property(x => x.CreatedBy).HasColumnName(@"created_by").HasColumnType("int").IsOptional();
            Property(x => x.UpdatedAt).HasColumnName(@"updated_at").HasColumnType("datetime2").IsOptional();
            Property(x => x.UpdatedBy).HasColumnName(@"updated_by").HasColumnType("int").IsOptional();
            Property(x => x.IsDeleted).HasColumnName(@"is_deleted").HasColumnType("bit").IsRequired();
            Property(x => x.RowVersion).HasColumnName(@"row_version").HasColumnType("timestamp").IsRequired().IsFixedLength().HasMaxLength(8).IsRowVersion().IsConcurrencyToken();

            // Foreign keys
            HasOptional(a => a.User).WithMany(b => b.Site).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // FK_site_user
        }
    }

}
// </auto-generated>
