// <auto-generated>

using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.Spatial;

namespace KitchenEquipmentDemo.Enterprise.Data
{
    // site_equipment_history
    public class SiteEquipmentHistoryConfiguration : EntityTypeConfiguration<SiteEquipmentHistory>
    {
        public SiteEquipmentHistoryConfiguration()
            : this("dbo")
        {
        }

        public SiteEquipmentHistoryConfiguration(string schema)
        {
            ToTable("site_equipment_history", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.EquipmentId).HasColumnName(@"equipment_id").HasColumnType("int").IsRequired();
            Property(x => x.SiteId).HasColumnName(@"site_id").HasColumnType("int").IsOptional();
            Property(x => x.Action).HasColumnName(@"action").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(20);
            Property(x => x.ActionAt).HasColumnName(@"action_at").HasColumnType("datetime2").IsRequired();
            Property(x => x.ActionBy).HasColumnName(@"action_by").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Site).WithMany(b => b.SiteEquipmentHistory).HasForeignKey(c => c.SiteId).WillCascadeOnDelete(false); // FK_hist_site
            HasRequired(a => a.Equipment).WithMany(b => b.SiteEquipmentHistory).HasForeignKey(c => c.EquipmentId).WillCascadeOnDelete(false); // FK_hist_equipment
        }
    }

}
// </auto-generated>
