// <auto-generated>

using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.Spatial;
using KitchenEquipmentDemo.Enterprise.Data.Models;

namespace KitchenEquipmentDemo.Enterprise.Data.Mappings
{
    // user_registration_request
    public class UserRegistrationRequestConfiguration : EntityTypeConfiguration<UserRegistrationRequest>
    {
        public UserRegistrationRequestConfiguration()
            : this("dbo")
        {
        }

        public UserRegistrationRequestConfiguration(string schema)
        {
            ToTable("user_registration_request", schema);
            HasKey(x => x.RequestId);

            Property(x => x.RequestId).HasColumnName(@"request_id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.FirstName).HasColumnName(@"first_name").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.LastName).HasColumnName(@"last_name").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.EmailAddress).HasColumnName(@"email_address").HasColumnType("nvarchar").IsOptional().HasMaxLength(256);
            Property(x => x.UserName).HasColumnName(@"user_name").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.UserType).HasColumnName(@"user_type").HasColumnType("nvarchar").IsOptional().HasMaxLength(20);
            Property(x => x.PasswordHash).HasColumnName(@"password_hash").HasColumnType("varbinary").IsRequired().HasMaxLength(64);
            Property(x => x.PasswordSalt).HasColumnName(@"password_salt").HasColumnType("varbinary").IsRequired().HasMaxLength(16);
            Property(x => x.Status).HasColumnName(@"status").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(20);
            Property(x => x.CreatedAt).HasColumnName(@"created_at").HasColumnType("datetime2").IsRequired();
            Property(x => x.ReviewedBy).HasColumnName(@"reviewed_by").HasColumnType("int").IsOptional();
            Property(x => x.ReviewedAt).HasColumnName(@"reviewed_at").HasColumnType("datetime2").IsOptional();
            Property(x => x.ReviewNote).HasColumnName(@"review_note").HasColumnType("nvarchar").IsOptional().HasMaxLength(400);

            // Foreign keys
            HasOptional(a => a.User).WithMany(b => b.UserRegistrationRequest).HasForeignKey(c => c.ReviewedBy).WillCascadeOnDelete(false); // FK_urr_reviewed_by
        }
    }

}
// </auto-generated>
